import { FormGroup, FormBuilder, Validators } from '@angular/forms';

export class ClientInfoGroup {
  clientInfoForm: FormGroup;
  constructor(private fb: FormBuilder) {
    this.clientInfoForm = this.fb.group({
      clientId: [null],
      name: [null, Validators.required],
      clientStatus: this.fb.group({ clientStatusId: [null, Validators.required],status: [null] }),
      product: this.fb.group({ productId: [null],productName: [null]  }),
      terminatingDate: [null],
      consultant: this.fb.group({ userId: [null] ,firstName: [null],lastName: [null] }),
      accountManager: this.fb.group({ userId: [null] ,firstName: [null] ,lastName: [null] }),
      access: this.fb.group({ accessId: [null],accessType: [null]  }),
      contractRenewalDate: [null],
      relationshipManager: this.fb.group({ userId: [null] ,firstName: [null] ,lastName: [null]  }),
      hrisSystem: this.fb.group({ hrisSystemId: [null],systemName: [null]  }),
      insurer: this.fb.group({ insurerId: [null],name: [null]  }),
      planRenewalDate: [null],
      goLiveDate: [null],
      eapEmployerProvided: this.fb.group({ eapEmployerProvidedId: [null] ,providerName:[null]}),
      mercer365URL: [null],
      hrisTransmission: [null],
      hrisFrequency: [null],
      additionalFileLoads: [null],
      pepm: [null],
      inflationClause: [null],
      wellnessCalendarOfEvents: [null],
      measureYourHealth: [null],
      virtualCare: null,
      mso: [null],
      careQuest: [null],
      healthCoaching: [null],
      getFit: [null],
      improveYourSleep: [null],
      nutritionProfile: [null],
      drugProfile: [null],
      virtualPhysiotherapy: [null],
      functionalFitness: [null],
      findATherapist: [null],
      digitalMentalHealthTherapy: this.fb.group({ digitalMentalHealthTherapyId: [null] ,providerName:[]}),
      eapPortalProvider: [null],
      improveYourSleepEAP: [null],
      freeResourcesToHelp: [null],
      creditCounselling: [null],
      homeAndAutoMarsh: [null],
      homeAndAutoEmployerProvided: [null],
      willSupport: [null],
      petInsurance: [null],
      retireeInsurance: [null],
      discounts: [null],
      vetster: [null],
      tutoring: [null],
      givingBack: [null],
      caregiving: [null],
      clientSpecificOffering1: [null],
      clientSpecificOffering2: [null],
      clientSpecificOffering3: [null],
      clientSpecificOffering4: [null],
      clientSpecificOffering5: [null],
      clientSpecificOffering6: [null],
      clientSpecificOffering7: [null],
      wellnessWallet: [null],
      wellnessWalletCarryover: [null],
      payrollProcessingFrequency:this.fb.group({ payrollProcessingFrequencyId: [null] ,frequency:[]}),
      quarterlyAdministratorAccessReview: [null],
      payrollCalendar: this.fb.group({ payrollCalendarId: [null] ,calendarName:[]}),
      saToolkitUpdate: [null],
      wellnessCampaignRenewal: [null],
      wellnessWalletResetReload: [null],
      allowedToCommunicateDirectly: [null],
      commentsNotes: [null],
    });
  }
}
